
DROP TABLE CLASSROOMS; 
DROP TABLE GRADES;
DROP TABLE TRANSFER_CREDITS; 
DROP TABLE REGISTERS 
DROP TABLE COURSCES 
DROP TABLE CIS_DEPARTMENTS 
DROP TABLE BOOKS
DROP TABLE BOOKSSTORES 
DROP TABLE PAYMENTES 
DROP TABLE BUSINESSOFFICE 
DROP TABLE EMERGENCY_CONTACTS;
DROP TABLE GRADUATE_WITH;
DROP TABLE ADMISSIONS


CREATE TABLE ADMISSIONS
 (
     ADMISSIONID# int,	
     STUDENTID# int,
     FIRSTNAME VARCHAR(20) NOT NULL,
     LASTNAME VARCHAR(20) NOT NULL,
     SSN int unique,
     DOB VARCHAR(6) NOT NULL,
	 [ADDRESS] VARCHAR(MAX),
	 PHONENUMBER VARCHAR(MAX),
             CONSTRAINT ADMISSIONS_ADMISSIONID#_PK PRIMARY KEY(ADMISSIONID#),	    
             CONSTRAINT ADMISSIONS_STUDENTID_UQ UNIQUE (STUDENTID#),
			 --CONSTRAINT ADMISSIONS_DEPARTMENTID#_FK FOREIGN KEY REFERENCES DEPARTMENTS(DEPARTMENTID#)
 );
 CREATE TABLE TRANSFER_CREDITS
(
	TRANSFER_CREDITSID# int,
	STUDENTID# INT,
	COURSCEID# int,
		CONSTRAINT TRANSFER_CREDITS_TRANSCREDITID# PRIMARY KEY(TRANSFER_CREDITSID#),
		CONSTRAINT TRANSFER_CREDITS_STUDENTID#_FK FOREIGN KEY(STUDENTID#)REFERENCES ADMISSIONS(STUDENTID#)
);

 CREATE TABLE GRADUATE_WITH
(
	GRADUATE_WITH# INT,
	STUDENTID# INT UNIQUE,
	DEGREE VARCHAR(10),
	DEPLOMA VARCHAR(10),
	CERTFICATE VARCHAR(10),
		CONSTRAINT GRADUATE_WITHS_GRADUATE_WITH#_PK PRIMARY KEY(GRADUATE_WITH#),
		CONSTRAINT GRADUATE_WITH_STUDENTID#_FK FOREIGN KEY(STUDENTID#) REFERENCES ADMISSIONS(STUDENTID#)

);
 CREATE TABLE CIS_DEPARTMENTS
(
	DEPARTMENTID# INT,
	STUDENTID# INT,
	PROGRAM_MAJOR VARCHAR(max),
	
		CONSTRAINT CIS_DEPARTMENTS_DEPARTMENTID#_PK PRIMARY KEY(DEPARTMENTID#), 	
		CONSTRAINT CIS_DEPARTMENTS_STUDENTID#_FK FOREIGN KEY(STUDENTID#) REFERENCES ADMISSIONS(STUDENTID#)		
);

 CREATE TABLE EMERGENCY_CONTACTS
 (
     EMERGENCY_CONTACT# int,
     [ADDRES] VARCHAR(MAX),
     PHONE VARCHAR(20),    
     STUDENTID# int UNIQUE,
             CONSTRAINT EMERGENCY_CONTACTS_EMERGENCY_CONTACTID#_PK PRIMARY KEY(EMERGENCY_CONTACT#),             
             CONSTRAINT EMERGENCY_CONTACTS_STUDENTID#_FK FOREIGN KEY(STUDENTID#) REFERENCES ADMISSIONS(STUDENTID#)
);




CREATE TABLE BUSINESSOFFICE
(
   BUSINESSID# int,
   AID# int, 
   LONE# int,  
   YEAR VARCHAR(20),
   SEMESTER VARCHAR(20),   
   STUDENTID# int,
  	CONSTRAINT BUSINESSOFFICE_BUSINESSID#_PK PRIMARY KEY(BUSINESSID#),
	CONSTRAINT BUSINESSOFFICE_STUDENTID#_FK FOREIGN KEY(STUDENTID#)	REFERENCES ADMISSIONS(STUDENTID#)
);

CREATE TABLE PAYMENTES
(
   PAYMENTID# int,
   PAYMENTFOR VARCHAR(20),
   AMOUNT# int,
   BUSINESSID# int,
  	CONSTRAINT PAYMENTS_PAYMENTID#_PK PRIMARY KEY(PAYMENTID#),
	CONSTRAINT PAYMENTS_BUSINESSID#_FK FOREIGN KEY(BUSINESSID#) REFERENCES BUSINESSOFFICE(BUSINESSID#)
);

CREATE TABLE BOOKSSTORES
(
	BOOKSTOREBOOKID# int,
	BOOKTITLE VARCHAR(40),
	ISBN# int UNIQUE,	
	PRICE INT,
	QUANTITY INT
		CONSTRAINT BOOKSTORES_BOOKSTOREBOOKID#_PK PRIMARY KEY(BOOKSTOREBOOKID#)		
);


CREATE TABLE BOOKS
(
	BOOKID# INT,
	ISBN# INT,
	PAYMENTID# INT
		CONSTRAINT BOOKS_BOOKID#_PK PRIMARY KEY(BOOKID#),
		CONSTRAINT BOOKS_PAYMENTID#_FK FOREIGN KEY(PAYMENTID#)REFERENCES PAYMENTES(PAYMENTID#),
		CONSTRAINT BOOKS_ISBN#_FK FOREIGN KEY(ISBN#)REFERENCES BOOKSSTORES(ISBN#)
);

CREATE TABLE COURSCES
(
	COURSCEID# int,
	COURSENAME VARCHAR(20),
	CRN int UNIQUE,
	CREDITHOURS int,
	DEPARTMENTID# int,
		CONSTRAINT COURSCES_COURSCEID#_PK PRIMARY KEY(COURSCEID#),
		CONSTRAINT COURSCES_DEPARTMENTID#_FK FOREIGN KEY(DEPARTMENTID#)	REFERENCES CIS_DEPARTMENTS(DEPARTMENTID#)
);
CREATE TABLE REGISTERS
(
	REGISTERID# int,
	SEMESTER VARCHAR(20),
	REGISTERDATE VARCHAR(20),
	COURSCEID# int,
		CONSTRAINT REGISTERS_REGISTERID#_PK PRIMARY KEY(REGISTERID#),
		CONSTRAINT REGISTERS_COURSCEID#_FK FOREIGN KEY(COURSCEID#)REFERENCES COURSCES(COURSCEID#)
);

CREATE TABLE GRADES
(
	GRADEID# int,
	GRADE INT,
	COURSCEID# int,
		CONSTRAINT GRADES_GRADEID#_PK PRIMARY KEY(GRADEID#),
		CONSTRAINT GRADES_COURSCEID#_FK FOREIGN KEY(COURSCEID#)REFERENCES COURSCES(COURSCEID#)
);
CREATE TABLE CLASSROOMS
(
	CLASSROOMID# int,
	DEPARTMENTID# int,
	classroom varchar(20),
		CONSTRAINT CLASSROOMS_CLASSROOMID#_PK PRIMARY KEY(CLASSROOMID#),
		CONSTRAINT CLASSROOMS_DEPARTMENTID#_FK FOREIGN KEY(DEPARTMENTID#)REFERENCES CIS_DEPARTMENTS(DEPARTMENTID#)
);



	